//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCheckIn.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentalCheckIn.Locales.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was created. An account confirmation link has been sent to your email..
        /// </summary>
        public static string AccountCreatedConfirmationEmailSent {
            get {
                return ResourceManager.GetString("AccountCreatedConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Action_Close_Label {
            get {
                return ResourceManager.GetString("Action.Close.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Apartment fee must be greater than 0..
        /// </summary>
        public static string ApartmentFeeRange {
            get {
                return ResourceManager.GetString("ApartmentFeeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment fee is required..
        /// </summary>
        public static string ApartmentFeeRequired {
            get {
                return ResourceManager.GetString("ApartmentFeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Apartment name is required..
        /// </summary>
        public static string ApartmentNameRequired {
            get {
                return ResourceManager.GetString("ApartmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Check-in date is required..
        /// </summary>
        public static string CheckInDateRequired {
            get {
                return ResourceManager.GetString("CheckInDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckInTimeRequired.
        /// </summary>
        public static string CheckInTimeRequired {
            get {
                return ResourceManager.GetString("CheckInTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out Date must be after Check-In Date..
        /// </summary>
        public static string CheckOutDateAfterCheckIn {
            get {
                return ResourceManager.GetString("CheckOutDateAfterCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out date is required..
        /// </summary>
        public static string CheckOutDateRequired {
            get {
                return ResourceManager.GetString("CheckOutDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Check-out time is required..
        /// </summary>
        public static string CheckOutTimeRequired {
            get {
                return ResourceManager.GetString("CheckOutTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Email.
        /// </summary>
        public static string ConfirmEmailButtonText {
            get {
                return ResourceManager.GetString("ConfirmEmailButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        public static string ConfirmEmailPrimaryMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailPrimaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string ConfirmPasswordCompareError {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password field is required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Contact_Mobile_Label {
            get {
                return ResourceManager.GetString("Contact.Mobile.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load resources..
        /// </summary>
        public static string CouldNotLoadResources {
            get {
                return ResourceManager.GetString("CouldNotLoadResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string Document_PassportNumber_Label {
            get {
                return ResourceManager.GetString("Document.PassportNumber.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face ID registration failed.
        /// </summary>
        public static string FaceID_Registration_Failed {
            get {
                return ResourceManager.GetString("FaceID.Registration.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Face ID registration successful!.
        /// </summary>
        public static string FaceID_Registration_Success {
            get {
                return ResourceManager.GetString("FaceID.Registration.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during Face ID registration..
        /// </summary>
        public static string FaceID_Registration_UnexpectedError {
            get {
                return ResourceManager.GetString("FaceID.Registration.UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Fee.
        /// </summary>
        public static string Fee_Apartment_Label {
            get {
                return ResourceManager.GetString("Fee.Apartment.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Apartment.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  First name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK-IN FORM.
        /// </summary>
        public static string Form_CheckIn_Title {
            get {
                return ResourceManager.GetString("Form.CheckIn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string General_Details_Label {
            get {
                return ResourceManager.GetString("General.Details.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adults.
        /// </summary>
        public static string Guest_Adults_Label {
            get {
                return ResourceManager.GetString("Guest.Adults.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest details.
        /// </summary>
        public static string Guest_Details_Label {
            get {
                return ResourceManager.GetString("Guest.Details.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        public static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Meter reading must be greater than 0..
        /// </summary>
        public static string KwhAtCheckInRange {
            get {
                return ResourceManager.GetString("KwhAtCheckInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter reading is required..
        /// </summary>
        public static string KwhAtCheckInRequired {
            get {
                return ResourceManager.GetString("KwhAtCheckInRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest&apos;s signature.
        /// </summary>
        public static string Label_GuestsSignature {
            get {
                return ResourceManager.GetString("Label_GuestsSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Label_Place {
            get {
                return ResourceManager.GetString("Label_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account.
        /// </summary>
        public static string LoginSecMessage {
            get {
                return ResourceManager.GetString("LoginSecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string LoginSignUpLink {
            get {
                return ResourceManager.GetString("LoginSignUpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is required..
        /// </summary>
        public static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nights.
        /// </summary>
        public static string Nights {
            get {
                return ResourceManager.GetString("Nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Number of nights must be greater than 0..
        /// </summary>
        public static string NumberOfNightsGreaterThanZero {
            get {
                return ResourceManager.GetString("NumberOfNightsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP code required.
        /// </summary>
        public static string OTPCodeRequired {
            get {
                return ResourceManager.GetString("OTPCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number cannot exceed 50 characters..
        /// </summary>
        public static string PassportNrMaxLength {
            get {
                return ResourceManager.GetString("PassportNrMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number is required..
        /// </summary>
        public static string PassportNrRequired {
            get {
                return ResourceManager.GetString("PassportNrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Rreset Link.
        /// </summary>
        public static string Password_R_RequestButtonText {
            get {
                return ResourceManager.GetString("Password_R_RequestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        public static string Password_R_RequestPrimaryMessage {
            get {
                return ResourceManager.GetString("Password_R_RequestPrimaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address associated with your account.
        /// </summary>
        public static string Password_R_RequestSecMessage {
            get {
                return ResourceManager.GetString("Password_R_RequestSecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long, have an upper letter, a lowercase letter, a number, and a special character..
        /// </summary>
        public static string PasswordRegexError {
            get {
                return ResourceManager.GetString("PasswordRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Password.
        /// </summary>
        public static string PasswordResetButtonText {
            get {
                return ResourceManager.GetString("PasswordResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string PasswordResetErrorMessage {
            get {
                return ResourceManager.GetString("PasswordResetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string PasswordResetPrimaryMessage {
            get {
                return ResourceManager.GetString("PasswordResetPrimaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully reset.
        /// </summary>
        public static string PasswordResetSuccessMessage {
            get {
                return ResourceManager.GetString("PasswordResetSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string Payment_Total_Label {
            get {
                return ResourceManager.GetString("Payment.Total.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price summary.
        /// </summary>
        public static string Price_Summary_Label {
            get {
                return ResourceManager.GetString("Price.Summary.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string Price_Total_Label {
            get {
                return ResourceManager.GetString("Price.Total.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest checked-in successfully!.
        /// </summary>
        public static string Quest_CheckIn_Success {
            get {
                return ResourceManager.GetString("Quest.CheckIn.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was created successfully..
        /// </summary>
        public static string RegisterAccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("RegisterAccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string RegisterCreateAccount {
            get {
                return ResourceManager.GetString("RegisterCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account.
        /// </summary>
        public static string RegisterSecMessage {
            get {
                return ResourceManager.GetString("RegisterSecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;BoldExample&quot; xml:space=&quot;preserve&quot;&gt;
        ///  &lt;value&gt;Please scan the following QR code with an authenticator &lt;strong&gt;app&lt;/strong&gt; like &lt;strong&gt;Microsoft Authenticator&lt;/strong&gt; on your phone, or enter the secret code manually. Then proceed to &lt;a href=&quot;login&quot;&gt; Login&lt;/a&gt;&lt;/value&gt;
        ///&lt;/data&gt;.
        /// </summary>
        public static string RegisterSuccessPrimaryMessage {
            get {
                return ResourceManager.GetString("RegisterSuccessPrimaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing this form, the tenant declares to agree with the (house) rules from the &quot;IMPORTANT&quot; handbook and the general terms and conditions of Snowy Lodge..
        /// </summary>
        public static string Rental_Agreement_Signature_Info {
            get {
                return ResourceManager.GetString("Rental.Agreement.Signature.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy consumption up to 30 kWh per day is included in the rental price! For additional use, $0.20 per kWh will be charged at check-out.
        /// </summary>
        public static string Rental_EnergyConsumption_CheckBox {
            get {
                return ResourceManager.GetString("Rental.EnergyConsumption.CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received alarm remote control, remote control sliding gate, house key, gate key, and room keys..
        /// </summary>
        public static string Rental_ReceivedKeys_Info {
            get {
                return ResourceManager.GetString("Rental.ReceivedKeys.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Deposit.
        /// </summary>
        public static string SecurityDeposit_Label {
            get {
                return ResourceManager.GetString("SecurityDeposit.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security deposit must be greater than 0..
        /// </summary>
        public static string SecurityDepositRange {
            get {
                return ResourceManager.GetString("SecurityDepositRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security deposit is required..
        /// </summary>
        public static string SecurityDepositRequired {
            get {
                return ResourceManager.GetString("SecurityDepositRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected2FARegexError.
        /// </summary>
        public static string Selected2FARegexError {
            get {
                return ResourceManager.GetString("Selected2FARegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a two-factor authentication method..
        /// </summary>
        public static string Selected2FARequired {
            get {
                return ResourceManager.GetString("Selected2FARequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The signature is required..
        /// </summary>
        public static string Signature_Required {
            get {
                return ResourceManager.GetString("Signature.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later..
        /// </summary>
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported 2FA method selected..
        /// </summary>
        public static string Unsupported2FAMethod {
            get {
                return ResourceManager.GetString("Unsupported2FAMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification is invalid, please contact support..
        /// </summary>
        public static string VerificationInvalid {
            get {
                return ResourceManager.GetString("VerificationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your identity.
        /// </summary>
        public static string VerifyTOTPPrimaryMessage {
            get {
                return ResourceManager.GetString("VerifyTOTPPrimaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;data name=&quot;BoldExample&quot; xml:space=&quot;preserve&quot;&gt;
        ///  &lt;value&gt;Enter the one time password that is displayed in your &lt;strong&gt;authenticator app&lt;/strong&gt; &lt;/value&gt;
        ///&lt;/data&gt;.
        /// </summary>
        public static string VerifyTOTPSecMessage {
            get {
                return ResourceManager.GetString("VerifyTOTPSecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerifyTOTPVerifyText {
            get {
                return ResourceManager.GetString("VerifyTOTPVerifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwind, Relax, and Stay Awhile.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your role.
        /// </summary>
        public static string Your_role {
            get {
                return ResourceManager.GetString("Your role", resourceCulture);
            }
        }
    }
}
